# Generated by Django 4.1.1 on 2022-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_meals_discription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=40, verbose_name='email')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата и Время')),
            ],
        ),
    ]
